[world]
kind = "WorldContract"
class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
original_class_hash = "0x3715f072aa1c07be724249fcda8b0322687f6c5c585eebc4402d162649c707c"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x57952d454a1152dce4b3fe13f128377e403b1987d0eab7b93bc8178d3f7e219"
transaction_hash = "0xc993d186861cdabe9cade3bd83dadef011ee91a43faf1874a815ea4130accd"
block_number = 13
seed = "pistols64-1"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x3cbe76182dc3c32fdb22240f2d6f4b444624c1b7865ea7951f9ff9d06987b5c"
class_hash = "0x4bb3c568f7832411d975a55be86eccb0fe15ce8a9f9ef42029320125fe8bf6a"
original_class_hash = "0x4bb3c568f7832411d975a55be86eccb0fe15ce8a9f9ef42029320125fe8bf6a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/pistols64-actions-67633088.json"
reads = []
writes = ["pistols64-Challenge"]
init_calldata = []
tag = "pistols64-actions"
systems = ["move"]
manifest_name = "pistols64-actions-67633088"

[[models]]
kind = "DojoModel"
class_hash = "0x39380a0b122e24f3eb936b3501a2fd7938902ff7be0a01c160b872ee8a81e40"
original_class_hash = "0x39380a0b122e24f3eb936b3501a2fd7938902ff7be0a01c160b872ee8a81e40"
abi = "manifests/dev/deployment/abis/models/pistols64-Challenge-4a2b5cb4.json"
tag = "pistols64-Challenge"
qualified_path = "pistols64::models::challenge::challenge"
manifest_name = "pistols64-Challenge-4a2b5cb4"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "address_a"
type = "ContractAddress"
key = false

[[models.members]]
name = "address_b"
type = "ContractAddress"
key = false

[[models.members]]
name = "duelist_name_a"
type = "felt252"
key = false

[[models.members]]
name = "duelist_name_b"
type = "felt252"
key = false

[[models.members]]
name = "message"
type = "felt252"
key = false

[[models.members]]
name = "state"
type = "ChallengeState"
key = false

[[models.members]]
name = "winner"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1bea27311f9f7e32323c3ba966b86cf57044cb9bdd85a154aab2ecb88de4d32"
original_class_hash = "0x1bea27311f9f7e32323c3ba966b86cf57044cb9bdd85a154aab2ecb88de4d32"
abi = "manifests/dev/deployment/abis/models/pistols64-Round-41ec1aaa.json"
tag = "pistols64-Round"
qualified_path = "pistols64::models::round::round"
manifest_name = "pistols64-Round-41ec1aaa"

[[models.members]]
name = "duel_id"
type = "u128"
key = true

[[models.members]]
name = "round_number"
type = "u8"
key = true

[[models.members]]
name = "shot_a"
type = "Shot"
key = false

[[models.members]]
name = "shot_b"
type = "Shot"
key = false
